### ISSUE TITLE
Setup Guide: Convert Unicode Quotes To ASCII

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access.github.io#5] opened 2022-07-28 18:51 UTC
The setup guide tells the player to enter a specific string into the Steam launcher that requires quotes. The problem is that the site uses the fansy left quote right quote symbols, which Steam will break on. I've had to help a few people resolve this issue.
Can the setup guide be changed to use standard ASCII quotes?
"C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\StardewModdingAPI.exe" %command%

**Comment by khanshoaib3** [comment] 2022-08-12 11:21
That may have caused by the theme, i'll diable it.

**Comment by khanshoaib3** [comment] 2022-08-12 11:43
Just updated the wiki, this should be fixed, in case it still persists, reopen this issue.

**Closed by khanshoaib3** 2022-08-12 11:43 UTC
